/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['Cormorant Garamond', 'Georgia', 'serif'],
        body: ['DM Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        surface: {
          primary: 'var(--color-bg-primary)',
          secondary: 'var(--color-bg-secondary)',
          tertiary: 'var(--color-bg-tertiary)',
          card: 'var(--color-bg-card)',
          input: 'var(--color-bg-input)',
          dropdown: 'var(--color-bg-dropdown)',
          elevated: 'var(--color-bg-elevated)',
        },
        'border-card': 'var(--color-border-card)',
        accent: {
          DEFAULT: 'var(--color-accent)',
          hover: 'var(--color-accent-hover)',
          text: 'var(--color-accent-text)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          accent: 'var(--color-border-accent)',
          subtle: 'var(--color-border-subtle)',
          muted: 'var(--color-border-muted)',
        },
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-label': 'var(--color-text-label)',
        'text-dim': 'var(--color-text-dim)',
        status: {
          success: 'var(--color-status-success)',
          'success-muted': 'var(--color-status-success-muted)',
          warning: 'var(--color-status-warning)',
          'warning-muted': 'var(--color-status-warning-muted)',
          'warning-text': 'var(--color-status-warning-text)',
          error: 'var(--color-status-error)',
          'error-muted': 'var(--color-status-error-muted)',
          info: 'var(--color-status-info)',
          'info-muted': 'var(--color-status-info-muted)',
          pending: 'var(--color-status-pending)',
          inactive: 'var(--color-status-inactive)',
          paused: 'var(--color-status-paused)',
        },
        plan: {
          free: 'var(--color-plan-free)',
          standard: 'var(--color-plan-standard)',
          plus: 'var(--color-plan-plus)',
          premium: 'var(--color-plan-premium)',
          pro: 'var(--color-plan-pro)',
          elite: 'var(--color-plan-elite)',
          ultimate: 'var(--color-plan-ultimate)',
          enterprise: 'var(--color-plan-enterprise)',
        },
        tool: {
          story: 'var(--color-tool-story)',
          video: 'var(--color-tool-video)',
          compare: 'var(--color-tool-compare)',
          prompts: 'var(--color-tool-prompts)',
          images: 'var(--color-tool-images)',
          tts: 'var(--color-tool-tts)',
        },
        eval: {
          pacing: 'var(--color-eval-pacing)',
          consistency: 'var(--color-eval-consistency)',
          character: 'var(--color-eval-character)',
          plot: 'var(--color-eval-plot)',
          tone: 'var(--color-eval-tone)',
          overall: 'var(--color-eval-overall)',
        },
        action: {
          success: 'var(--color-action-success)',
          'success-hover': 'var(--color-action-success-hover)',
          info: 'var(--color-action-info)',
          'info-hover': 'var(--color-action-info-hover)',
          warning: 'var(--color-action-warning)',
          'warning-hover': 'var(--color-action-warning-hover)',
          orange: 'var(--color-action-orange)',
          'orange-hover': 'var(--color-action-orange-hover)',
          purple: 'var(--color-action-purple)',
          'purple-hover': 'var(--color-action-purple-hover)',
          indigo: 'var(--color-action-indigo)',
          'indigo-hover': 'var(--color-action-indigo-hover)',
        },
        model: {
          entry: 'var(--color-model-entry)',
          'entry-accent': 'var(--color-model-entry-border)',
          'standard-a': 'var(--color-model-standard-a)',
          'standard-a-accent': 'var(--color-model-standard-a-border)',
          'standard-b': 'var(--color-model-standard-b)',
          'standard-b-accent': 'var(--color-model-standard-b-border)',
          'plus-a': 'var(--color-model-plus-a)',
          'plus-a-accent': 'var(--color-model-plus-a-border)',
          'plus-b': 'var(--color-model-plus-b)',
          'plus-b-accent': 'var(--color-model-plus-b-border)',
          'pro-a': 'var(--color-model-pro-a)',
          'pro-a-accent': 'var(--color-model-pro-a-border)',
          'pro-b': 'var(--color-model-pro-b)',
          'pro-b-accent': 'var(--color-model-pro-b-border)',
          elite: 'var(--color-model-elite)',
          'elite-accent': 'var(--color-model-elite-border)',
          ultimate: 'var(--color-model-ultimate)',
          'ultimate-accent': 'var(--color-model-ultimate-border)',
        },
      },
      backgroundColor: {
        'status-success': 'var(--color-status-success-bg)',
        'status-warning': 'var(--color-status-warning-bg)',
        'status-error': 'var(--color-status-error-bg)',
        'status-info': 'var(--color-status-info-bg)',
        'status-pending': 'var(--color-status-pending-bg)',
        'status-inactive': 'var(--color-status-inactive-bg)',
        'status-paused': 'var(--color-status-paused-bg)',
        'plan-free': 'var(--color-plan-free-bg)',
        'plan-standard': 'var(--color-plan-standard-bg)',
        'plan-plus': 'var(--color-plan-plus-bg)',
        'plan-premium': 'var(--color-plan-premium-bg)',
        'plan-pro': 'var(--color-plan-pro-bg)',
        'plan-elite': 'var(--color-plan-elite-bg)',
        'plan-ultimate': 'var(--color-plan-ultimate-bg)',
        'plan-enterprise': 'var(--color-plan-enterprise-bg)',
        'tool-story': 'var(--color-tool-story-bg)',
        'tool-video': 'var(--color-tool-video-bg)',
        'tool-compare': 'var(--color-tool-compare-bg)',
        'tool-prompts': 'var(--color-tool-prompts-bg)',
        'tool-images': 'var(--color-tool-images-bg)',
        'tool-tts': 'var(--color-tool-tts-bg)',
        'overlay-hover': 'var(--white-overlay-hover)',
        'overlay-active': 'var(--white-overlay-active)',
        'overlay-selected': 'var(--white-overlay-selected)',
      },
      borderColor: {
        'status-success': 'var(--color-status-success-border)',
        'status-warning': 'var(--color-status-warning-border)',
        'status-error': 'var(--color-status-error-border)',
        'status-info': 'var(--color-status-info-border)',
        'status-pending': 'var(--color-status-pending-border)',
        'status-inactive': 'var(--color-status-inactive-border)',
        'status-paused': 'var(--color-status-paused-border)',
        'plan-free': 'var(--color-plan-free-border)',
        'plan-standard': 'var(--color-plan-standard-border)',
        'plan-plus': 'var(--color-plan-plus-border)',
        'plan-premium': 'var(--color-plan-premium-border)',
        'plan-pro': 'var(--color-plan-pro-border)',
        'plan-elite': 'var(--color-plan-elite-border)',
        'plan-ultimate': 'var(--color-plan-ultimate-border)',
        'plan-enterprise': 'var(--color-plan-enterprise-border)',
      },
      borderRadius: {
        token: 'var(--radius-md)',
      },
      spacing: {
        section: 'var(--section-spacing)',
      },
    },
  },
  plugins: [],
};
