/**
 * Word-level subtitle timing for the Step 4 preview narration.
 *
 * Generated by `~/Desktop/testTS/transcribe_preview_audio.py` from one of
 * the preview videos in Supabase storage:
 *   …/websitestuff/ExampleVideoWithImageGen/01_none__none__none.mp4
 *
 * All preview videos share the same audio track, so a single dataset is
 * used for every variant. To regenerate, re-run the python script and
 * paste the resulting JSON arrays back into this file.
 *
 * Cue grouping rules mirror gcloudfunctions/subtitles.py
 * (`_group_words_into_cues`) so the on-screen preview matches the final
 * burned-in subtitles as closely as possible.
 */

export interface PreviewWord {
  word: string;
  start: number;
  end: number;
}

export interface PreviewCue {
  start: number;
  end: number;
  text: string;
  words: PreviewWord[];
}

export interface PreviewSubtitles {
  /** Total duration of the source preview video, in seconds. */
  audioDuration: number;
  /** Flat word list with start/end timestamps in seconds. */
  words: PreviewWord[];
  /** Pre-grouped cues for each subtitle mode. `karaoke` reuses `phrase`. */
  cues: {
    phrase: PreviewCue[];
    single_word: PreviewCue[];
  };
}

export const PREVIEW_SUBTITLES: PreviewSubtitles = {
  audioDuration: 12.023023,
  words: [
    { word: 'The',      start: 0.03,  end: 0.11  },
    { word: 'morning',  start: 0.11,  end: 0.39  },
    { word: 'sun',      start: 0.39,  end: 0.85  },
    { word: 'filtered', start: 0.85,  end: 1.57  },
    { word: 'through',  start: 1.57,  end: 2.09  },
    { word: 'the',      start: 2.09,  end: 2.31  },
    { word: 'apple',    start: 2.31,  end: 2.71  },
    { word: 'blossoms', start: 2.71,  end: 3.15  },
    { word: 'like',     start: 3.15,  end: 3.77  },
    { word: 'liquid',   start: 3.77,  end: 4.25  },
    { word: 'gold,',    start: 4.25,  end: 5.13  },
    { word: 'casting',  start: 5.87,  end: 6.07  },
    { word: 'dancing',  start: 6.07,  end: 6.55  },
    { word: 'shadows',  start: 6.55,  end: 7.23  },
    { word: 'across',   start: 7.23,  end: 8.01  },
    { word: "Max's",    start: 8.01,  end: 8.89  },
    { word: 'backyard', start: 8.89,  end: 9.33  },
    { word: 'meadow',   start: 9.33,  end: 10.21 },
    { word: 'where',    start: 10.21, end: 10.89 },
    { word: 'five',     start: 10.89, end: 11.23 },
    { word: 'white',    start: 11.23, end: 11.85 },
  ],
  cues: {
    phrase: [
      {
        start: 0.03,
        end: 2.71,
        text: 'The morning sun filtered through the apple',
        words: [
          { word: 'The',      start: 0.03, end: 0.11 },
          { word: 'morning',  start: 0.11, end: 0.39 },
          { word: 'sun',      start: 0.39, end: 0.85 },
          { word: 'filtered', start: 0.85, end: 1.57 },
          { word: 'through',  start: 1.57, end: 2.09 },
          { word: 'the',      start: 2.09, end: 2.31 },
          { word: 'apple',    start: 2.31, end: 2.71 },
        ],
      },
      {
        start: 2.71,
        end: 5.13,
        text: 'blossoms like liquid gold,',
        words: [
          { word: 'blossoms', start: 2.71, end: 3.15 },
          { word: 'like',     start: 3.15, end: 3.77 },
          { word: 'liquid',   start: 3.77, end: 4.25 },
          { word: 'gold,',    start: 4.25, end: 5.13 },
        ],
      },
      {
        start: 5.87,
        end: 10.21,
        text: "casting dancing shadows across Max's backyard meadow",
        words: [
          { word: 'casting',  start: 5.87, end: 6.07  },
          { word: 'dancing',  start: 6.07, end: 6.55  },
          { word: 'shadows',  start: 6.55, end: 7.23  },
          { word: 'across',   start: 7.23, end: 8.01  },
          { word: "Max's",    start: 8.01, end: 8.89  },
          { word: 'backyard', start: 8.89, end: 9.33  },
          { word: 'meadow',   start: 9.33, end: 10.21 },
        ],
      },
      {
        start: 10.21,
        end: 11.85,
        text: 'where five white',
        words: [
          { word: 'where', start: 10.21, end: 10.89 },
          { word: 'five',  start: 10.89, end: 11.23 },
          { word: 'white', start: 11.23, end: 11.85 },
        ],
      },
    ],
    single_word: [
      { start: 0.03,  end: 0.21,  text: 'The',      words: [{ word: 'The',      start: 0.03,  end: 0.11  }] },
      { start: 0.11,  end: 0.39,  text: 'morning',  words: [{ word: 'morning',  start: 0.11,  end: 0.39  }] },
      { start: 0.39,  end: 0.85,  text: 'sun',      words: [{ word: 'sun',      start: 0.39,  end: 0.85  }] },
      { start: 0.85,  end: 1.57,  text: 'filtered', words: [{ word: 'filtered', start: 0.85,  end: 1.57  }] },
      { start: 1.57,  end: 2.09,  text: 'through',  words: [{ word: 'through',  start: 1.57,  end: 2.09  }] },
      { start: 2.09,  end: 2.31,  text: 'the',      words: [{ word: 'the',      start: 2.09,  end: 2.31  }] },
      { start: 2.31,  end: 2.71,  text: 'apple',    words: [{ word: 'apple',    start: 2.31,  end: 2.71  }] },
      { start: 2.71,  end: 3.15,  text: 'blossoms', words: [{ word: 'blossoms', start: 2.71,  end: 3.15  }] },
      { start: 3.15,  end: 3.77,  text: 'like',     words: [{ word: 'like',     start: 3.15,  end: 3.77  }] },
      { start: 3.77,  end: 4.25,  text: 'liquid',   words: [{ word: 'liquid',   start: 3.77,  end: 4.25  }] },
      { start: 4.25,  end: 5.13,  text: 'gold,',    words: [{ word: 'gold,',    start: 4.25,  end: 5.13  }] },
      { start: 5.87,  end: 6.07,  text: 'casting',  words: [{ word: 'casting',  start: 5.87,  end: 6.07  }] },
      { start: 6.07,  end: 6.55,  text: 'dancing',  words: [{ word: 'dancing',  start: 6.07,  end: 6.55  }] },
      { start: 6.55,  end: 7.23,  text: 'shadows',  words: [{ word: 'shadows',  start: 6.55,  end: 7.23  }] },
      { start: 7.23,  end: 8.01,  text: 'across',   words: [{ word: 'across',   start: 7.23,  end: 8.01  }] },
      { start: 8.01,  end: 8.89,  text: "Max's",    words: [{ word: "Max's",    start: 8.01,  end: 8.89  }] },
      { start: 8.89,  end: 9.33,  text: 'backyard', words: [{ word: 'backyard', start: 8.89,  end: 9.33  }] },
      { start: 9.33,  end: 10.21, text: 'meadow',   words: [{ word: 'meadow',   start: 9.33,  end: 10.21 }] },
      { start: 10.21, end: 10.89, text: 'where',    words: [{ word: 'where',    start: 10.21, end: 10.89 }] },
      { start: 10.89, end: 11.23, text: 'five',     words: [{ word: 'five',     start: 10.89, end: 11.23 }] },
      { start: 11.23, end: 11.85, text: 'white',    words: [{ word: 'white',    start: 11.23, end: 11.85 }] },
    ],
  },
};
